name = "SADflow"
uuid = "6ff62a4f-9ff6-447e-9b6c-e161468b6cbd"
authors = ["Pietro Butti <pietro.butti.fl@gmail.com>"]
version = "0.1.0"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ConcreteStructs = "0.2.3"
Lux = "1.22.1"
MLUtils = "0.4.8"
NNlib = "0.9.31"
Random = "1.11.0"
StatsBase = "0.34.6"
