name = "SADflow"
uuid = "6ff62a4f-9ff6-447e-9b6c-e161468b6cbd"
authors = ["Pietro Butti <pietro.butti.fl@gmail.com>"]
version = "0.1.0"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
WeightInitializers = "d49dbf32-c5c2-4618-8acc-27bb2598ef2d"

[compat]
ConcreteStructs = "0.2.3"
Enzyme = "0.13.86"
ForwardDiff = "1.0.0"
Lux = "1.22.1"
LuxCore = "1.5.0"
MLUtils = "0.4.8"
NNlib = "0.9.31"
Random = "1.11.0"
Reactant = "0.2.170"
StatsBase = "0.34.6"
WeightInitializers = "1.3.0"

[extras]
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
LuxLib = "82251201-b29d-42c6-8e01-566dec8acb11"
